#pragma once

#include <stdbool.h>

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generated by tools/convert_gui_logo.py. */
extern const lv_image_dsc_t university_logo_image;
extern const bool university_logo_available;

#ifdef __cplusplus
}
#endif
