#!/usr/bin/env bash
set -euo pipefail

# ESP32-P4 AI backend + sleep-mode flashing front-end
#
# Existing hybrid behavior (backward compatible):
#   ./utilities/esp_AI_flashing.sh dl
#   ./utilities/esp_AI_flashing.sh fp32
#   ./utilities/esp_AI_flashing.sh nn
#
# New single-sleep diagnostic modes:
#   ./utilities/esp_AI_flashing.sh dl   -d
#   ./utilities/esp_AI_flashing.sh dl   -l
#   ./utilities/esp_AI_flashing.sh fp32 -d
#   ./utilities/esp_AI_flashing.sh fp32 -l
#   ./utilities/esp_AI_flashing.sh nn   -d
#   ./utilities/esp_AI_flashing.sh nn   -l
#
#   -d / --deep   -> DEEP-ONLY: direct Active -> Deep-sleep after 7 s
#                    of inactivity. Light-sleep is completely skipped.
#
#   -l / --light  -> LIGHT-ONLY: enter Light-sleep after 7 s of inactivity.
#                    Automatic Deep-sleep is completely disabled.
#
# No -d/-l       -> HYBRID: preserve the existing Light-sleep-at-15-s then
#                    Deep-sleep-at-30-s policy.
#
# Optional port can be supplied in any position after the backend:
#   ./utilities/esp_AI_flashing.sh dl -d /dev/ttyACM1
#   ./utilities/esp_AI_flashing.sh dl /dev/ttyACM1 -d

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

MODE="${1:-}"
shift || true

case "$MODE" in
    dl|espdl|esp-dl)
        BACKEND="dl"
        BACKEND_LABEL="ESP-DL S8"
        ;;
    fp32|tflm|tflm-fp32)
        BACKEND="fp32"
        BACKEND_LABEL="TFLM-FP32"
        ;;
    nn|int8|esp-nn|tflm-int8|tflm-int8-espnn)
        BACKEND="nn"
        BACKEND_LABEL="TFLM-INT8 + ESP-NN"
        ;;
    *)
        echo "Usage: $0 {dl|fp32|nn} [-d|-l] [PORT]"
        echo
        echo "Sleep selection:"
        echo "  -d, --deep    Direct Deep-sleep only after 7 s inactivity"
        echo "  -l, --light   Light-sleep only after 7 s inactivity"
        echo "  no flag       Existing hybrid 15 s Light -> 30 s Deep"
        echo
        echo "Examples:"
        echo "  $0 dl -d"
        echo "  $0 dl -l"
        echo "  $0 nn -d /dev/ttyACM1"
        echo "  $0 fp32 /dev/ttyACM0 -l"
        exit 2
        ;;
esac

PORT="/dev/ttyACM0"
SLEEP_POLICY="hybrid"
SLEEP_POLICY_MACRO="APP_SLEEP_POLICY_HYBRID"
SLEEP_LABEL="HYBRID: Light 15 s -> Deep 30 s"
SLEEP_FLAG_SEEN=0

for ARG in "$@"; do
    case "$ARG" in
        -d|--deep)
            if [[ "$SLEEP_FLAG_SEEN" -eq 1 && "$SLEEP_POLICY" != "deep" ]]; then
                echo "[ERROR] Choose only one of -d or -l."
                exit 2
            fi
            SLEEP_FLAG_SEEN=1
            SLEEP_POLICY="deep"
            SLEEP_POLICY_MACRO="APP_SLEEP_POLICY_DEEP_ONLY"
            SLEEP_LABEL="DEEP-ONLY: Active -> Deep after 7 s"
            ;;
        -l|--light)
            if [[ "$SLEEP_FLAG_SEEN" -eq 1 && "$SLEEP_POLICY" != "light" ]]; then
                echo "[ERROR] Choose only one of -d or -l."
                exit 2
            fi
            SLEEP_FLAG_SEEN=1
            SLEEP_POLICY="light"
            SLEEP_POLICY_MACRO="APP_SLEEP_POLICY_LIGHT_ONLY"
            SLEEP_LABEL="LIGHT-ONLY: Light after 7 s; Deep disabled"
            ;;
        /dev/*)
            PORT="$ARG"
            ;;
        *)
            echo "[ERROR] Unknown argument: $ARG"
            echo "Usage: $0 {dl|fp32|nn} [-d|-l] [PORT]"
            exit 2
            ;;
    esac
done

SLEEP_HEADER="$PROJECT_ROOT/src/main/include/config/sleep_mode_selection.h"
mkdir -p "$(dirname "$SLEEP_HEADER")"

TMP_HEADER="${SLEEP_HEADER}.tmp.$$"
cat > "$TMP_HEADER" <<EOF
#pragma once

/*
 * Generated by utilities/esp_AI_flashing.sh.
 * Selected flash mode: $SLEEP_LABEL
 */
#define APP_SLEEP_POLICY_HYBRID       0
#define APP_SLEEP_POLICY_LIGHT_ONLY   1
#define APP_SLEEP_POLICY_DEEP_ONLY    2

#define APP_SLEEP_POLICY $SLEEP_POLICY_MACRO
EOF
mv "$TMP_HEADER" "$SLEEP_HEADER"

echo "============================================================"
echo " AI backend + sleep policy selected"
echo "============================================================"
echo "Backend   : $BACKEND_LABEL"
echo "Sleep     : $SLEEP_LABEL"
echo "Timeout   : $([[ "$SLEEP_POLICY" == "hybrid" ]] && echo "15 s / 30 s" || echo "7 s")"
echo "Port      : $PORT"
echo "Header    : $SLEEP_HEADER"
echo "============================================================"
echo

if [[ ! -f "$PROJECT_ROOT/tools/flash_ai_backend.sh" ]]; then
    echo "[ERROR] Missing: $PROJECT_ROOT/tools/flash_ai_backend.sh"
    exit 1
fi

exec "$PROJECT_ROOT/tools/flash_ai_backend.sh" "$BACKEND" "$PORT"
