#pragma once

/*
 * Generated by utilities/esp_AI_flashing.sh.
 * Selected flash mode: DEEP-ONLY: Active -> Deep after 7 s
 */
#define APP_SLEEP_POLICY_HYBRID       0
#define APP_SLEEP_POLICY_LIGHT_ONLY   1
#define APP_SLEEP_POLICY_DEEP_ONLY    2

#define APP_SLEEP_POLICY APP_SLEEP_POLICY_DEEP_ONLY
