#!/usr/bin/env bash
set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$TOOLS_DIR/.." && pwd)"
HEADER="$PROJECT_ROOT/src/main/include/config/ai_backend_selection.h"

usage() {
    cat <<'EOF'
Usage:
  ./tools/select_ai_backend.sh espdl
  ./tools/select_ai_backend.sh tflm-fp32
EOF
}

BACKEND="${1:-}"

case "$BACKEND" in
    espdl)
        MACRO="APP_AI_BACKEND_ESPDL"
        LABEL="ESP-DL"
        ;;
    tflm-fp32|tflm|fp32)
        MACRO="APP_AI_BACKEND_TFLM_FP32"
        LABEL="TFLM-FP32 (BlazeFace + MobileFaceNet)"
        ;;
    *)
        usage
        exit 2
        ;;
esac

mkdir -p "$(dirname "$HEADER")"

cat > "$HEADER" <<EOF
#pragma once

/*
 * Generated by tools/select_ai_backend.sh.
 * Re-run the script instead of editing this file during A/B measurements.
 */
#ifndef APP_AI_BACKEND
#define APP_AI_BACKEND $MACRO
#endif
EOF

echo "============================================================"
echo " AI backend selected"
echo "============================================================"
echo "Backend : $LABEL"
echo "Header  : $HEADER"
echo
echo "Next:"
echo "  ./tools/flash_ai_backend.sh $BACKEND /dev/ttyACM0"
