#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HEADER="$PROJECT_ROOT/src/main/include/config/ai_backend_selection.h"

MODE="${1:-}"

case "$MODE" in
    dl|espdl|esp-dl)
        CANONICAL="espdl"
        DEFINE="APP_AI_BACKEND_ESPDL"
        LABEL="ESP-DL S8"
        ;;
    fp32|tflm|tflm-fp32)
        CANONICAL="tflm-fp32"
        DEFINE="APP_AI_BACKEND_TFLM_FP32"
        LABEL="TFLM-FP32"
        ;;
    nn|int8|esp-nn|tflm-int8|tflm-int8-espnn)
        CANONICAL="tflm-int8"
        DEFINE="APP_AI_BACKEND_TFLM_INT8"
        LABEL="TFLM-INT8 + ESP-NN"
        ;;
    *)
        echo "Usage: $0 {dl|fp32|nn}"
        echo
        echo "  dl    -> ESP-DL S8"
        echo "  fp32  -> TFLM-FP32"
        echo "  nn    -> TFLM-INT8 + ESP-NN"
        exit 2
        ;;
esac

mkdir -p "$(dirname "$HEADER")"

tmp="${HEADER}.tmp.$$"
cat > "$tmp" <<EOF
#pragma once

/*
 * Generated by tools/select_ai_backend.sh.
 * Do not edit manually during A/B measurements.
 */
#ifndef APP_AI_BACKEND
#define APP_AI_BACKEND ${DEFINE}
#endif
EOF
mv "$tmp" "$HEADER"

echo "============================================================"
echo " AI backend selected"
echo "============================================================"
echo "Mode      : $MODE"
echo "Canonical : $CANONICAL"
echo "Backend   : $LABEL"
echo "Header    : $HEADER"
echo "============================================================"
